### PR TITLE
Pin maturin version in GitHub Actions

### PR DESCRIPTION
**Pull request by arturomf94**
## Description

This will fix the build fail for the release. I think it's better to pin down the version we will use here so that changes in Maturin don't break our pipeline. However I also think it's time to update the Maturin version we're using, so I created a separate issue for that: https://github.com/OpenMined/sycret/issues/39

## How has this been tested?
Ran locally

## Checklist
- [x] I have followed the [Contribution Guidelines](https://github.com/OpenMined/.github/blob/master/CONTRIBUTING.md) and [Code of Conduct](https://github.com/OpenMined/.github/blob/master/CODE_OF_CONDUCT.md)
- [x] I have commented my code following the [OpenMined Styleguide](https://github.com/OpenMined/.github/blob/master/STYLEGUIDE.md)
- [x] I have labeled this PR with the relevant [Type labels](https://github.com/OpenMined/.github/labels?q=Type%3A)
- [x] My changes are covered by tests

### CODE REVIEW

**Comment by tholop** [comment]
Thanks @arturomf94! Does this PR also fix the current issue with the `manylinux` flag?

**Comment by arturomf94** [comment]
It should, momentarily. But I also raised this ticket: https://github.com/PyO3/maturin/issues/636. It has been fixed already so I will open a PR to update the maturin version.

**Comment by arturomf94** [comment]
I actually think it's better to merge this first, though, because we wouldn't want to rush into a newer version of maturin if we're not sure that it will work for us. Fortunately, maturin was working just fine before, so we should be ok with this fix and we can leave the update for later, whenever there's a release with the patch from https://github.com/PyO3/maturin/issues/636. What do you think?

**Comment by tholop** [comment]
I agree, thanks @arturomf94 (and nice for reaching out upstream). I'll merge!

**Pull request merged**
